# Site settings
title: Eric Beezhold
email: ewbeez82@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging for fun. This cover's anything that I find interesting. Devops, cloud computing, API's, cars.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ewbeez82.github.io" # the base hostname & protocol for your site
twitter_username: ewbeez82
github_username:  ewbeez82

# Build settings
markdown: kramdown
